export default [
  require('./dummy/basic.js').default,
  require('./dummy/failing-1.js').default,
  require('./dummy/failing-2.js').default,
  require('./dummy/failing-3.js').default,
  require('./dummy/failing-4.js').default,
  require('./dummy/failing-5.js').default,
  require('./dummy/sleep-1.js').default,
  require('./dummy/sleep-2.js').default,
  require('./dummy/sleep-3.js').default,
  require('./dummy/error-1.js').default,
  require('./dummy/error-2.js').default,
  require('./dummy/timeout.js').default,
  require('./dummy/setup-teardown-1.js').default,
  require('./dummy/setup-teardown-2.js').default,
  require('./dummy/setup-teardown-3.js').default,
  require('./dummy/setup-teardown-4.js').default,
  require('./dummy/repeat-1.js').default,
  require('./dummy/repeat-2.js').default,
  require('./dummy/repeat-3.js').default,
  require('./dummy/repeat-4.js').default,
  require('./dummy/repeat-5.js').default,
  require('./dummy/repeat-6.js').default,
  require('./dummy/repeat-7.js').default,
  require('./dummy/repeat-8.js').default,
  require('./dummy/repeat-9.js').default,

  // require('./dummy.test.js').default,
  // require('./helpers.test.js').default,
  // require('./youtube.test.js').default,
  // require('./timeout-requests.test.js').default,
  // require('./timeout-custom.test.js').default,
]
