export default [
  require('../testrunner/testcases/basic.js').default,
  require('../testrunner/testcases/failing-1.js').default,
  require('../testrunner/testcases/failing-2.js').default,
  require('../testrunner/testcases/failing-3.js').default,
  require('../testrunner/testcases/failing-4.js').default,
  require('../testrunner/testcases/failing-5.js').default,
  require('../testrunner/testcases/sleep-1.js').default,
  require('../testrunner/testcases/sleep-2.js').default,
  require('../testrunner/testcases/sleep-3.js').default,
  require('../testrunner/testcases/error-1.js').default,
  require('../testrunner/testcases/error-2.js').default,
  require('../testrunner/testcases/timeout.js').default,
  require('../testrunner/testcases/setup-teardown-1.js').default,
  require('../testrunner/testcases/setup-teardown-2.js').default,
  require('../testrunner/testcases/setup-teardown-3.js').default,
  require('../testrunner/testcases/setup-teardown-4.js').default,
  require('../testrunner/testcases/repeat-1.js').default,
  require('../testrunner/testcases/repeat-2.js').default,
  require('../testrunner/testcases/repeat-3.js').default,
  require('../testrunner/testcases/repeat-4.js').default,
  require('../testrunner/testcases/repeat-5.js').default,
  require('../testrunner/testcases/repeat-6.js').default,
  require('../testrunner/testcases/repeat-7.js').default,
  require('../testrunner/testcases/repeat-8.js').default,
  require('../testrunner/testcases/repeat-9.js').default,
  require('../testrunner/testcases/repeat-10.js').default,
  require('../testrunner/testcases/repeat-11.js').default,
  require('../testrunner/testcases/context-1.js').default,
  require('../testrunner/testcases/data-1.js').default,
  require('../testrunner/testcases/data-2.js').default,
  require('../testrunner/testcases/test-validate-1.js').default,
  require('../testrunner/testcases/test-validate-2.js').default,
  require('../testrunner/testcases/test-validate-3.js').default,
  require('../testrunner/testcases/logger.js').default,
  require('../testrunner/testcases/steps-as-object.js').default,
  require('../testrunner/testcases/extending-1.js').default,
  require('../testrunner/testcases/extending-2.js').default,
  require('../testrunner/testcases/extending-3.js').default,
  require('../testrunner/testcases/extending-4.js').default,
  require('../testrunner/testcases/extending-5.js').default,
  require('../testrunner/testcases/nested-tests-1.js').default,
  require('../testrunner/testcases/nested-tests-2.js').default,
  require('../testrunner/testcases/nested-tests-3.js').default,
  require('../testrunner/testcases/validation-helpers-1.js').default,
  require('../testrunner/testcases/validation-helpers-2.js').default,

  // require('./dummy.test.js').default,
  // require('./helpers.test.js').default,
  // require('./youtube.test.js').default,
  // require('./timeout-requests.test.js').default,
  // require('./timeout-custom.test.js').default,
]
